name: Hello World

on:
  workflow_dispatch:
    
jobs:
  hello-world:
    name: Hello World Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Greet
        run: echo "Hello World!"
      - run: ls -al
      - uses: actions/checkout@v3.5.3
      - run: ls -al 
