name: Hello World

on:
  workflow_dispatch:
    
jobs:
  hello-world:
    name: Hello World Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Greet
        run: echo "Hello World!"
      - name: List directory before checkout
        run: ls -al
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: List directory after checkout
        run: ls -al 
