name: Hello World

on:
  workflow_dispatch:
    
jobs:
  hello-world:
    name: Hello World Job
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello World!"
      - run: ls -al
      - uses: actions/checkout@v2
      - run: ls -al 
